### ISSUE TITLE
Question: Was GCN Used?

### ISSUE THREAD

**Issue by zhanwenchen** [ZhuGeKongKong/SGG-G2S#3]
Hi,

I saw that you had GCN layers defined in the code but you didn't seem to end up using it. Is that correct? If so, why did you comment it out? I'm interested in using GCN in SGG.

The relevant code is at

https://github.com/ZhuGeKongKong/SGG-G2S/blob/main/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py#L337-L338

**Comment by ZhuGeKongKong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    The gcn layer is based on https://github.com/tkipf/pygcn. However, we do not use it in our method. If you are interested in GCN, you should check it.
    
        
        

        
    

    On 2/16/2022 09:24，Zhanwen ***@***.***> wrote： 



Hi,
I saw that you had GCN layers defined in the code but you didn't seem to end up using it. Is that correct? If so, why did you comment it out? I'm interested in using GCN in SGG.
The relevant code is at
https://github.com/ZhuGeKongKong/SGG-G2S/blob/main/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py#L337-L338

**Comment by zhanwenchen** [comment]
多谢指点！能问一下为什么没用呢？我很怕有坑 😂

**Comment by ZhuGeKongKong** [comment]
If you want use the GCN layers, the adjacency matrix of the GCN is important for the performance, but the construction of the adjacent matrix is a problem.
