### ISSUE TITLE
How to make conf_mat_freq_train.npy and conf_mat_freq_train.npy?

### ISSUE THREAD

**Issue by zhanwenchen** [ZhuGeKongKong/SGG-G2S#4]
Would you please provide instructions on how you made the conf_mat_freq_train.npy and the (commented out) conf_mat_adj_mat.npy? I was about to locate conf_mat_freq_train.npy in the repo.

**Comment by ZhuGeKongKong** [comment]
the construction of the confusion matrix in the evaluation script.
https://github.com/ZhuGeKongKong/SGG-G2S/blob/main/maskrcnn_benchmark/data/datasets/evaluation/vg/sgg_eval.py#Line255  (SGConfMat)

And we provide the constructed matrix in https://github.com/ZhuGeKongKong/SGG-G2S/blob/main/misc/conf_mat_freq_train.npy

**Comment by zhanwenchen** [comment]
Thank you! This is very helpful.
